[package]
name = "premium-friday"
version = "0.1.0"
authors = ["k.hamada <k.hamada.1988@gmail.com>"]

[dependencies]
chrono = "0.4.6"
warp = "0.1.6"
log = "0.4"
pretty_env_logger = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
