[package]
name = "premium-friday"
version = "0.1.0"
authors = ["k.hamada <k.hamada.1988@gmail.com>"]
edition = "2018"

[dependencies]
http = "0.1"
chrono = "0.4.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
